### ISSUE TITLE
Finishing up checklist.

### ISSUE THREAD

**Issue by knightss27** [knightss27/capr#3]
- [x] Download button
- [x] Add headwords
- [x] Refishing status
- [x] Board scrolling overflow
- [x] Passing FST compiler errors to interface
- [ ] Mysterious missing stuff from FST output
- [x] Write README for development / project structure / how to use
- [x] Investigate packaging in foma (or at least providing good instructions)
